### PR TITLE
Round 1 adding Clear speaker referent ids and labels to quotation data

### PR DESCRIPTION
**Pull request by RickBrannan**
I've added ids to referents as well as a label (usually gloss-based, unless one is available from reference chain or reference set data). The JSON and TSV with speaker data now also includes the referent data from Clear.

### CODE REVIEW

**Comment by jonathanrobie** [comment]
This is a matter of taste, but I would normally leave things out if they are not present, so I would prefer not to see the "null" entries and empty strings in places like this:

image

**Comment by RickBrannan** [comment]
Thanks, Jonathan. I'll look into the empty string in the SDBH list (and if it occurs in other contexts). I'll see what I can do about the `null`, but that's how the object deserializes.

**Comment by RickBrannan** [comment]
@jonathanrobie , I believe I've removed the null and empty properties from the character semantic data.

**Comment by jonathanrobie** [comment]
Looks good - go ahead and merge.

**Pull request merged**
